- name: Install, restart with PM2, reload Nginx (ssh)
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.VM_SSH_HOST }}
    username: ${{ secrets.SSH_USER_NAME }}
    password: ${{ secrets.SSH_PASSWORD }}
    port: ${{ secrets.SSH_PORT }}
    script: |
      set -euo pipefail

      APP_DIR="/home/saajra/htdocs/saajra.com"
      TMP_DIR="/tmp/savan_website_deploy"

      # Make sure paths exist and owned by root (since PM2 runs as root)
      sudo mkdir -p "$APP_DIR" "$TMP_DIR"
      sudo chown -R root:root "$APP_DIR" "$TMP_DIR"

      # Unpack the new code into the app directory
      sudo tar -xzf "$TMP_DIR/deploy.tgz" -C "$APP_DIR"

      # Run the rest **as root login shell** so PM2 sees the same universe
      sudo -i bash <<'EOS'
      set -euo pipefail

      export PM2_HOME="/root/.pm2"          # use the same PM2 list as root
      APP_DIR="/home/saajra/htdocs/saajra.com"

      cd "$APP_DIR"

      # If nvm is installed for root, use it; otherwise fall back to system node
      if [ -s "/root/.nvm/nvm.sh" ]; then
        export NVM_DIR="/root/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm install --lts >/dev/null 2>&1 || true
        nvm use --lts
        hash -r
      fi

      # Ensure pm2 is available (global) – harmless if already installed
      if ! command -v pm2 >/dev/null 2>&1; then
        npm i -g pm2
      fi

      node -v
      npm -v
      pm2 -v

      # Install deps & build
      if [ -f package-lock.json ]; then
        npm ci --no-audit --no-fund
      else
        npm install --no-audit --no-fund
      fi
      npm run build

      # Restart existing root-owned process; else start fresh on PORT=3003
      if pm2 describe savan-website-app >/dev/null 2>&1; then
        pm2 restart savan-website-app --update-env
      else
        PORT=3003 pm2 start npm --name "savan-website-app" -- start
      fi

      pm2 save
      # ensure PM2 auto-starts on boot for root (idempotent)
      pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true
      EOS

      # Finally reload nginx
      sudo systemctl reload nginx || sudo systemctl restart nginx
